<?php

namespace Database\Seeders;

use App\Models\Place;
use Illuminate\Database\Seeder;

class PlaceSeeder extends Seeder
{
    public function run(): void
    {
        $places = [
            [
                'category_id' => 1,
                'name' => 'Plage d\'Agadir',
                'address' => 'Promenade de la Baie d\'Agadir',
                'lat' => 30.4207,
                'lng' => -9.5801,
                'rating' => 4.5,
                'description' => 'La célèbre plage d\'Agadir avec accès PMR et rampes.',
                'wheelchair' => true,
                'ramp' => true,
                'elevator' => false,
                'adapted_toilet' => true,
                'pmr_parking' => true,
            ],
            [
                'category_id' => 1,
                'name' => 'Plage de Taghazout',
                'address' => 'Taghazout, Route d\'Essaouira',
                'lat' => 30.5401,
                'lng' => -9.8320,
                'rating' => 4.2,
                'description' => 'Plage paisible mais accès limité pour PMR.',
                'wheelchair' => false,
                'ramp' => false,
                'elevator' => false,
                'adapted_toilet' => false,
                'pmr_parking' => false,
            ],
            [
                'category_id' => 2,
                'name' => 'Parc Olhao',
                'address' => 'Avenue Mohammed V',
                'lat' => 30.4278,
                'lng' => -9.5832,
                'rating' => 4.0,
                'description' => 'Parc municipal avec allées accessibles.',
                'wheelchair' => true,
                'ramp' => true,
                'elevator' => false,
                'adapted_toilet' => false,
                'pmr_parking' => true,
            ],
            [
                'category_id' => 3,
                'name' => 'CHU Agadir',
                'address' => 'Rue des Hôpitaux, Quartier Industriel',
                'lat' => 30.4342,
                'lng' => -9.5711,
                'rating' => 3.8,
                'description' => 'Centre hospitalier universitaire avec accès PMR.',
                'wheelchair' => true,
                'ramp' => true,
                'elevator' => true,
                'adapted_toilet' => true,
                'pmr_parking' => true,
            ],
            [
                'category_id' => 4,
                'name' => 'Wilaya d\'Agadir',
                'address' => 'Boulevard Mohammed V',
                'lat' => 30.4267,
                'lng' => -9.5892,
                'rating' => 3.5,
                'description' => 'Bâtiment administratif provincial.',
                'wheelchair' => true,
                'ramp' => true,
                'elevator' => false,
                'adapted_toilet' => false,
                'pmr_parking' => true,
            ],
            [
                'category_id' => 5,
                'name' => 'Café La Kasbah',
                'address' => 'Rue du Vieux Marché',
                'lat' => 30.4223,
                'lng' => -9.5861,
                'rating' => 4.3,
                'description' => 'Café traditionnel avec terrasse accessible.',
                'wheelchair' => true,
                'ramp' => true,
                'elevator' => false,
                'adapted_toilet' => false,
                'pmr_parking' => false,
            ],
            [
                'category_id' => 6,
                'name' => 'Hotel Royal Atlas',
                'address' => 'Chemin des Dunes, Founty',
                'lat' => 30.4123,
                'lng' => -9.5612,
                'rating' => 4.8,
                'description' => 'Hôtel luxueux avec accessibilité complète.',
                'wheelchair' => true,
                'ramp' => true,
                'elevator' => true,
                'adapted_toilet' => true,
                'pmr_parking' => true,
            ],
            [
                'category_id' => 6,
                'name' => 'Hotel Agadir',
                'address' => 'Avenue du Prince Héritier',
                'lat' => 30.4189,
                'lng' => -9.5756,
                'rating' => 3.9,
                'description' => 'Hôtel central, accès PMR partiel.',
                'wheelchair' => true,
                'ramp' => true,
                'elevator' => true,
                'adapted_toilet' => false,
                'pmr_parking' => true,
            ],
            [
                'category_id' => 7,
                'name' => 'Pharmacie Centrale',
                'address' => 'Place du 29 Mars',
                'lat' => 30.4245,
                'lng' => -9.5875,
                'rating' => 4.6,
                'description' => 'Pharmacie avec rampe d\'accès.',
                'wheelchair' => true,
                'ramp' => true,
                'elevator' => false,
                'adapted_toilet' => false,
                'pmr_parking' => false,
            ],
            [
                'category_id' => 7,
                'name' => 'Pharmacie Al Massar',
                'address' => 'Quartier Tiloguine',
                'lat' => 30.4398,
                'lng' => -9.5634,
                'rating' => 4.2,
                'description' => 'Pharmacie de quartier accessible.',
                'wheelchair' => true,
                'ramp' => false,
                'elevator' => false,
                'adapted_toilet' => false,
                'pmr_parking' => false,
            ],
            [
                'category_id' => 8,
                'name' => 'Restaurant Le Petit Comptoir',
                'address' => 'Rue de la Ville Basse',
                'lat' => 30.4212,
                'lng' => -9.5823,
                'rating' => 4.4,
                'description' => 'Restaurant français avec accès PMR.',
                'wheelchair' => true,
                'ramp' => true,
                'elevator' => false,
                'adapted_toilet' => true,
                'pmr_parking' => true,
            ],
            [
                'category_id' => 9,
                'name' => 'Musée du Patrimoine Amazigh',
                'address' => 'Quartier Kasbah',
                'lat' => 30.4167,
                'lng' => -9.5923,
                'rating' => 4.1,
                'description' => 'Musée de la culture berbère.',
                'wheelchair' => false,
                'ramp' => true,
                'elevator' => false,
                'adapted_toilet' => false,
                'pmr_parking' => false,
            ],
            [
                'category_id' => 10,
                'name' => 'Attijariwafa Bank',
                'address' => 'Boulevard Mohammed V, Centre Ville',
                'lat' => 30.4261,
                'lng' => -9.5887,
                'rating' => 4.0,
                'description' => 'Banque avec guichet PMR.',
                'wheelchair' => true,
                'ramp' => true,
                'elevator' => true,
                'adapted_toilet' => false,
                'pmr_parking' => true,
            ],
            [
                'category_id' => 10,
                'name' => 'Banque Populaire',
                'address' => 'Avenue Hassan II',
                'lat' => 30.4289,
                'lng' => -9.5856,
                'rating' => 3.8,
                'description' => 'Banque régionale avec accès partiellement accessible.',
                'wheelchair' => true,
                'ramp' => true,
                'elevator' => false,
                'adapted_toilet' => false,
                'pmr_parking' => false,
            ],
            [
                'category_id' => 8,
                'name' => 'Restaurant La Mer',
                'address' => 'Promenade de la Baie',
                'lat' => 30.4198,
                'lng' => -9.5789,
                'rating' => 4.7,
                'description' => 'Spécialités poissons et fruits de mer.',
                'wheelchair' => true,
                'ramp' => true,
                'elevator' => false,
                'adapted_toilet' => true,
                'pmr_parking' => true,
            ],
            [
                'category_id' => 4,
                'name' => 'Mairie d\'Agadir',
                'address' => 'Place Lahcen Lyousfi',
                'lat' => 30.4234,
                'lng' => -9.5891,
                'rating' => 3.6,
                'description' => 'Hôtel de ville avec rampes et ascenseur.',
                'wheelchair' => true,
                'ramp' => true,
                'elevator' => true,
                'adapted_toilet' => false,
                'pmr_parking' => true,
            ],
            [
                'category_id' => 5,
                'name' => 'Café Les Dunes',
                'address' => 'Founty Beach, Rue 18 N',
                'lat' => 30.4102,
                'lng' => -9.5645,
                'rating' => 4.1,
                'description' => 'Café avec vue sur océan.',
                'wheelchair' => true,
                'ramp' => true,
                'elevator' => false,
                'adapted_toilet' => false,
                'pmr_parking' => false,
            ],
            [
                'category_id' => 2,
                'name' => 'Jardin Ibn Battuta',
                'address' => 'Quartier Drargua',
                'lat' => 30.4523,
                'lng' => -9.5598,
                'rating' => 3.9,
                'description' => 'Jardin public récent avec espaces accessibles.',
                'wheelchair' => true,
                'ramp' => true,
                'elevator' => false,
                'adapted_toilet' => false,
                'pmr_parking' => true,
            ],
            [
                'category_id' => 9,
                'name' => 'Musée de la mémoire d\'Agadir',
                'address' => 'Rue du Palais Royal',
                'lat' => 30.4178,
                'lng' => -9.5912,
                'rating' => 4.3,
                'description' => 'Musée sur l\'histoire de la ville.',
                'wheelchair' => true,
                'ramp' => false,
                'elevator' => false,
                'adapted_toilet' => false,
                'pmr_parking' => false,
            ],
            [
                'category_id' => 8,
                'name' => 'Restaurant Dar L\'oudja',
                'address' => 'Kasbah, Rue de la Mosquée',
                'lat' => 30.4156,
                'lng' => -9.5945,
                'rating' => 4.5,
                'description' => 'Cuisine traditionnelle marocaine.',
                'wheelchair' => false,
                'ramp' => true,
                'elevator' => false,
                'adapted_toilet' => false,
                'pmr_parking' => false,
            ],
        ];

        foreach ($places as $place) {
            Place::create($place);
        }
    }
}